<%
rerun = File.file?('rerun.txt') ? IO.read('rerun.txt') : ""
rerun_opts = rerun.to_s.strip.empty? ? "--format #{ENV['CUCUMBER_FORMAT'] || 'progress'} features" : "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} #{rerun}"
std_opts = "-r features/support/ -r features/step_definitions --format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} --strict"
base_opts = "-r features/support/ -r features/step_definitions --strict"
smoke_opts = "-r smoke/support/ -r smoke/step_definitions --strict"
%>
default: <%= base_opts %> --format progress --tags ~@wip --tags ~@broken features
broken: <%= std_opts %> --tags @broken
all: <%= base_opts %> features
wip:  <%= std_opts %> --tags @wip features
rerun: <%= rerun_opts %> --format rerun --out rerun.txt --strict --tags ~@wip
usage: <%= base_opts %> --format usage --tags ~@wip
tags: <%= base_opts %> --format Cucumber::Formatter::TagCloud
guard: <%= base_opts %> --format progress --strict --tags ~@wip features
